INSERT INTO `libros` (`titulo`, `autor`, `editorial`, `fecha`, `tematica`) VALUES
('HARRY POTTER Y EL PRISIONERO DE AZKABAN', 'J.K ROWLING', 'SALAMANDRA', '2013-10-08', 'INFANTIL'),
('EL GRAN LABERINTO', 'FERNANDO SABATER PEREZ', 'ARIEL', '2012-10-16', 'FICCIÓN'),
('ROMEO Y JULIETA', 'WILLIAM SHAKESPEARE', 'SALAMANDRA', '2014-07-18', 'ROMANTICA'),
('LA CARTA ESFERICA', 'ARTURO PEREZ LOPEZ', 'SALAMANDRA', '2011-04-08', 'FICCION'),
('EL CODIGO DA VINCI', 'DAN BROWN', 'ARIEL', '2010-10-20', 'FICCION'),
('MUCHO RUIDO Y POCAS NUECES', 'WILLIAM SHAKESPEARE', 'SALAMANDRA', '2011-09-16', 'ROMANTICA'),
('PROTOCOLO', 'JOSE LOPEZ MURILLO', 'SALAMANDRA', '2014-01-21', 'SOCIAL'),
('LINUX', 'FERNANDO SABATER PEREZ', 'ARIEL', '2012-02-02', 'INFORMATICA'),
('EL TUMULTO', 'H.P LOVECRAFT', 'DEBATE', '2001-07-07', 'CIENCIA'),
('PERSONAJES MITICOS', 'RICHARD HOLLIGHAM', 'DEBATE', '2013-01-07', 'ENTRETENIMIENTO'),
('EL TIEMPO', 'J.K ROWLING', 'SALAMANDRA', '1999-11-05', 'CIENCIA'),
('DIETAS MEDITERRANEAS', 'ARTURO PEREZ LOPEZ', 'ARIEL', '2014-09-16', 'COCINA'),
('ANGELES Y DEMONIOS', 'DAN BROWN', 'ARIEL', '2014-09-21', 'FICCION'),
('FORTALEZA DIGITAL', 'DAN BROWN', 'ARIEL', '2011-04-19', 'FICCION'),
('CAPITAN ALATRISTE', 'ARTURO PEREZ REVERTE', 'ALFAGUARA', '2001-04-17', 'HISTORICA'),
('PIEL DE TAMBOR', 'ARTURO PEREZ REVERTE', 'ALFAGUARA', '2009-04-14', 'HISTORICA'),
('TIEMPOS DE COLERA', 'GABRIEL GARCIA', 'OVEJA NEGRA', '2002-08-04', 'HISTORICA'),
('NOTICIA DE UN SECUESTRO', 'GABRIEL GARCIA', 'ALFAGUARA', '2013-05-13', 'INTRIGA');


INSERT INTO `usuarios` (`usuario`, `password`) VALUES
('admin', '456'), ('itic', 'itic'), ('jonathan', '12345');